name: Update Google Trends

on:
  workflow_dispatch:  # 수동 실행을 위한 트리거

jobs:
  update-trends:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Install Node.js
      uses: actions/setup-node@v3  # Node.js 설정 추가
      with:
        node-version: '20'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests pytrends pandas

    - name: Run scraper
      run: |
        python scraper.py

    - name: Upload to Airtable
      env:
        AIRTABLE_API_KEY: ${{ secrets.AIRTABLE_API_KEY }}
        AIRTABLE_BASE_ID: ${{ secrets.AIRTABLE_BASE_ID }}
      run: |
        python upload_to_airtable.py
